# Logstash configuration for multiple pipelines

- pipeline.id: main
  path.config: "/usr/share/logstash/pipeline/logstash.conf"
  pipeline.workers: 2
  pipeline.batch.size: 125

- pipeline.id: csv
  path.config: "/usr/share/logstash/pipeline/csv-pipeline.conf"
  pipeline.workers: 1
  pipeline.batch.size: 125
